#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
source "$script_dir/../utils/os_detect.sh"

os=$(detect_os)

if [[ "$os" == "linux" ]]; then
    # Install dependencies
    install_packages unzip sudo

    # Download and install AWS CLI
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm awscliv2.zip
    rm -rf aws
elif [[ "$os" == "macos" ]]; then
    # Install dependencies
    if ! command -v brew &>/dev/null; then
        install_homebrew
    fi

    # Install AWS CLI
    brew install awscli
else
    echo "Unsupported operating system"
    exit 1
fi