#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
source "$script_dir/../utils/os_detect.sh"

os=$(detect_os)

if [[ "$os" == "linux" ]] || [[ "$os" == "macos" ]]; then
    # Install dependencies
    install_packages curl

    # Download and install Helm
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
    rm get_helm.sh
else
    echo "Unsupported operating system"
    exit 1
fi