#!/usr/bin/env bash
 
# FZF
git clone git@github.com:junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install --key-bindings --completion --no-update-rc

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
