#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
source "$script_dir/../utils/os_detect.sh"

os=$(detect_os)

if [[ "$os" == "linux" ]]; then
    # Linux packages
    install_packages unzip python3-venv libssl-dev pkg-config luarocks ripgrep fzf wl-clipboard
elif [[ "$os" == "macos" ]]; then
    # macOS packages
    install_packages unzip python openssl pkg-config luarocks ripgrep fzf
    # macOS doesn't need wl-clipboard as it has its own clipboard system
else
    echo "Unsupported operating system"
    exit 1
fi
