#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
source "$script_dir/../utils/os_detect.sh"

os=$(detect_os)

if [[ "$os" == "linux" ]] || [[ "$os" == "macos" ]]; then
    # Install dependencies
    if ! command -v brew &>/dev/null; then
        install_homebrew
    fi

    # Install pyenv
    brew install pyenv

    # Add to .zshrc if not already there
    if [ -f ~/.zshrc ] && ! grep -q "pyenv init" ~/.zshrc; then
        echo 'eval "$(pyenv init -)"' >> ~/.zshrc
    fi
else
    echo "Unsupported operating system"
    exit 1
fi