#!/usr/bin/env bash

# install option dependencies
sudo apt install ffmpeg 7zip jq poppler-utils fd-find ripgrep fzf zoxide imagemagick -y

git clone https://github.com/sxyazi/yazi.git $HOME/personal/yazi
cd $HOME/personal/yazi
cargo build --release --locked

sudo mv target/release/yazi target/release/ya /usr/local/bin/
